# Generated by Django 4.2 on 2024-06-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='cost',
        ),
    ]
