# Generated by Django 4.2 on 2024-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0002_remove_services_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
