# Generated by Django 4.2 on 2024-09-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0002_alter_workhour_from_hour_alter_workhour_to_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='workday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_hour', to='stylist.workday'),
        ),
    ]
