# Generated by Django 4.2 on 2024-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0003_services_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='category',
            field=models.ManyToManyField(related_name='category', to='stylist.servicecategorymodel'),
        ),
    ]
