# Generated by Django 4.2 on 2024-09-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0003_alter_workhour_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='stylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_day', to='stylist.stylist'),
        ),
        migrations.AlterField(
            model_name='workhour',
            name='workday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_hour', to='stylist.workday'),
        ),
    ]
