# Generated by Django 4.2 on 2024-09-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0006_specificworkhour_remove_workday_general_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimage',
            name='special_work_times',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='word_day',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='word_hour',
        ),
        migrations.AddField(
            model_name='stylist',
            name='special_work_times',
            field=models.ManyToManyField(blank=True, to='stylist.specificworkhour'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='word_day',
            field=models.ManyToManyField(blank=True, to='stylist.workday'),
        ),
        migrations.AddField(
            model_name='stylist',
            name='word_hour',
            field=models.ManyToManyField(blank=True, to='stylist.workhour'),
        ),
    ]
