# Generated by Django 4.2 on 2024-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0007_remove_portfolioimage_special_work_times_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='word_hour',
        ),
        migrations.RemoveField(
            model_name='workhour',
            name='workday',
        ),
        migrations.AddField(
            model_name='specificworkhour',
            name='hours',
            field=models.ManyToManyField(blank=True, to='stylist.workhour'),
        ),
        migrations.AddField(
            model_name='workday',
            name='hours',
            field=models.ManyToManyField(blank=True, to='stylist.workhour'),
        ),
    ]
