# Generated by Django 4.2 on 2024-09-18 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.UUID('19948263-32c4-449f-afc0-d1c8a1bee4bb'), editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('E-Mail', 'Email')], default='phone', max_length=10)),
                ('receiver', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
