# Generated by Django 4.2 on 2024-09-20 17:18

from django.db import migrations, models
import kavenegarapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kavenegarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=kavenegarapp.models.generate_otp, max_length=6),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
