# Generated by Django 4.2 on 2024-09-18 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kavenegarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('e89021d1-0679-47e4-9bcf-7f2a76c4b17c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
