# Generated by Django 4.2 on 2024-09-18 10:46

from django.db import migrations, models
import kavenegarapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kavenegarapp', '0002_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=kavenegarapp.models.generate_otp, max_length=4),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('207dbdd3-7d6c-4240-bbef-91af7970ad91'), editable=False, primary_key=True, serialize=False),
        ),
    ]
