# Generated by Django 4.2 on 2024-09-18 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kavenegarapp', '0003_alter_otprequest_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('866b1a6f-e93b-460b-bbde-e8e7947a73a2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
