# Generated by Django 4.2 on 2024-09-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveformmodel',
            name='hour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
