# Generated by Django 4.2 on 2024-09-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveform', '0002_alter_reserveformmodel_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveformmodel',
            name='day',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
