# Generated by Django 4.2 on 2024-06-03 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stylist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist.workday')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist.workhour')),
                ('paid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.reservation_paid')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist.services')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserve.reservation_status')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stylist.stylist')),
            ],
        ),
    ]
